// src/utils/constants.ts

export const ALL_COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia',
  'Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium',
  'Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei','Bulgaria',
  'Burkina Faso','Burundi','Cabo Verde','Cambodia','Cameroon','Canada','Central African Republic','Chad',
  'Chile','China','Colombia','Comoros','Congo (DRC)','Congo (Republic)','Costa Rica','Croatia','Cuba',
  'Cyprus','Czech Republic','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt',
  'El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France',
  'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau',
  'Guyana','Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel',
  'Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Laos',
  'Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Madagascar',
  'Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','Mexico',
  'Micronesia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia',
  'Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','North Korea',
  'North Macedonia','Norway','Oman','Pakistan','Palau','Palestine','Panama','Papua New Guinea',
  'Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Rwanda',
  'Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino',
  'Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore',
  'Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Korea','South Sudan',
  'Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syria','Taiwan','Tajikistan',
  'Tanzania','Thailand','Timor-Leste','Togo','Tonga','Trinidad and Tobago','Tunisia','Turkey',
  'Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States',
  'Uruguay','Uzbekistan','Vanuatu','Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe',
];

export const ALL_CURRENCIES = [
  { code:'AED',name:'UAE Dirham'},{ code:'AFN',name:'Afghan Afghani'},{ code:'ALL',name:'Albanian Lek'},
  { code:'AMD',name:'Armenian Dram'},{ code:'ARS',name:'Argentine Peso'},{ code:'AUD',name:'Australian Dollar'},
  { code:'AZN',name:'Azerbaijani Manat'},{ code:'BAM',name:'Bosnia Mark'},{ code:'BDT',name:'Bangladeshi Taka'},
  { code:'BGN',name:'Bulgarian Lev'},{ code:'BHD',name:'Bahraini Dinar'},{ code:'BIF',name:'Burundian Franc'},
  { code:'BND',name:'Brunei Dollar'},{ code:'BOB',name:'Bolivian Boliviano'},{ code:'BRL',name:'Brazilian Real'},
  { code:'BTN',name:'Bhutanese Ngultrum'},{ code:'BWP',name:'Botswanan Pula'},{ code:'BYN',name:'Belarusian Ruble'},
  { code:'BZD',name:'Belize Dollar'},{ code:'CAD',name:'Canadian Dollar'},{ code:'CHF',name:'Swiss Franc'},
  { code:'CLP',name:'Chilean Peso'},{ code:'CNY',name:'Chinese Yuan'},{ code:'COP',name:'Colombian Peso'},
  { code:'CRC',name:'Costa Rican Colón'},{ code:'CUP',name:'Cuban Peso'},{ code:'CZK',name:'Czech Koruna'},
  { code:'DKK',name:'Danish Krone'},{ code:'DOP',name:'Dominican Peso'},{ code:'DZD',name:'Algerian Dinar'},
  { code:'EGP',name:'Egyptian Pound'},{ code:'ETB',name:'Ethiopian Birr'},{ code:'EUR',name:'Euro'},
  { code:'GBP',name:'British Pound'},{ code:'GEL',name:'Georgian Lari'},{ code:'GHS',name:'Ghanaian Cedi'},
  { code:'GMD',name:'Gambian Dalasi'},{ code:'GTQ',name:'Guatemalan Quetzal'},{ code:'HKD',name:'Hong Kong Dollar'},
  { code:'HNL',name:'Honduran Lempira'},{ code:'HUF',name:'Hungarian Forint'},{ code:'IDR',name:'Indonesian Rupiah'},
  { code:'ILS',name:'Israeli Shekel'},{ code:'INR',name:'Indian Rupee'},{ code:'IQD',name:'Iraqi Dinar'},
  { code:'IRR',name:'Iranian Rial'},{ code:'ISK',name:'Icelandic Króna'},{ code:'JMD',name:'Jamaican Dollar'},
  { code:'JOD',name:'Jordanian Dinar'},{ code:'JPY',name:'Japanese Yen'},{ code:'KES',name:'Kenyan Shilling'},
  { code:'KGS',name:'Kyrgystani Som'},{ code:'KHR',name:'Cambodian Riel'},{ code:'KRW',name:'South Korean Won'},
  { code:'KWD',name:'Kuwaiti Dinar'},{ code:'KZT',name:'Kazakhstani Tenge'},{ code:'LAK',name:'Laotian Kip'},
  { code:'LBP',name:'Lebanese Pound'},{ code:'LKR',name:'Sri Lankan Rupee'},{ code:'LYD',name:'Libyan Dinar'},
  { code:'MAD',name:'Moroccan Dirham'},{ code:'MDL',name:'Moldovan Leu'},{ code:'MKD',name:'Macedonian Denar'},
  { code:'MMK',name:'Myanmar Kyat'},{ code:'MNT',name:'Mongolian Tugrik'},{ code:'MUR',name:'Mauritian Rupee'},
  { code:'MVR',name:'Maldivian Rufiyaa'},{ code:'MWK',name:'Malawian Kwacha'},{ code:'MXN',name:'Mexican Peso'},
  { code:'MYR',name:'Malaysian Ringgit'},{ code:'NAD',name:'Namibian Dollar'},{ code:'NGN',name:'Nigerian Naira'},
  { code:'NOK',name:'Norwegian Krone'},{ code:'NPR',name:'Nepalese Rupee'},{ code:'NZD',name:'New Zealand Dollar'},
  { code:'OMR',name:'Omani Rial'},{ code:'PEN',name:'Peruvian Sol'},{ code:'PHP',name:'Philippine Peso'},
  { code:'PKR',name:'Pakistani Rupee'},{ code:'PLN',name:'Polish Zloty'},{ code:'PYG',name:'Paraguayan Guarani'},
  { code:'QAR',name:'Qatari Riyal'},{ code:'RON',name:'Romanian Leu'},{ code:'RSD',name:'Serbian Dinar'},
  { code:'RUB',name:'Russian Ruble'},{ code:'RWF',name:'Rwandan Franc'},{ code:'SAR',name:'Saudi Riyal'},
  { code:'SEK',name:'Swedish Krona'},{ code:'SGD',name:'Singapore Dollar'},{ code:'SOS',name:'Somali Shilling'},
  { code:'SRD',name:'Surinamese Dollar'},{ code:'SYP',name:'Syrian Pound'},{ code:'THB',name:'Thai Baht'},
  { code:'TJS',name:'Tajikistani Somoni'},{ code:'TMT',name:'Turkmenistani Manat'},{ code:'TND',name:'Tunisian Dinar'},
  { code:'TRY',name:'Turkish Lira'},{ code:'TTD',name:'Trinidad Dollar'},{ code:'TWD',name:'New Taiwan Dollar'},
  { code:'TZS',name:'Tanzanian Shilling'},{ code:'UAH',name:'Ukrainian Hryvnia'},{ code:'UGX',name:'Ugandan Shilling'},
  { code:'USD',name:'US Dollar'},{ code:'UYU',name:'Uruguayan Peso'},{ code:'UZS',name:'Uzbekistani Som'},
  { code:'VND',name:'Vietnamese Dong'},{ code:'YER',name:'Yemeni Rial'},{ code:'ZAR',name:'South African Rand'},
  { code:'ZMW',name:'Zambian Kwacha'},{ code:'ZWL',name:'Zimbabwean Dollar'},
];

export const DOCUMENTS_LIST = [
  { key:'passport',          label:'Passport',                                                    required:true  },
  { key:'visa-scan',         label:'Visa Scan Copy (if in another country)',                       required:false },
  { key:'highest-edu-cert',  label:'Certificate of Highest Education',                            required:true  },
  { key:'transcript',        label:'Transcript of Highest Education',                             required:true  },
  { key:'reference-letters', label:'Two Reference Letters',                                       required:true  },
  { key:'bank-statement',    label:'Bank Statement',                                              required:false },
  { key:'guarantor-id',      label:'Valid ID Card or Passport Photo Page of Financial Guarantor', required:true  },
  { key:'criminal-record',   label:'Valid Certificate of Non-criminal Record',                    required:false },
  { key:'photo',             label:'Photo',                                                        required:true  },
  { key:'study-plan',        label:'Study / Research Plan',                                       required:false },
  { key:'resume',            label:'Resume',                                                      required:true  },
  { key:'language-prof',     label:'Language Proficiency',                                        required:false },
  { key:'extra-curricular',  label:'Extra Curricular Certificate',                                required:false },
];
